#!/bin/sh

set -e # to exit as soon as there is an error

opam_version=2.2.1
dune_version=3.7

hol2dk_commit=46927fe
hollight_commit=ea45176
lambdapi_version=2.5.1
ocaml_version=4.14.2
camlp5_version=8.02.01
coq_version=8.20.0

base=hol_upto_real
dump_simp_option=-before-hol
require=HOLLight_Real
jobs='-j32'

line() { echo '------------------------------------------------------------'; }

mkdir -p tmp
cd tmp

create_opam_switch() {
    line
    echo create opam switch reproduce ...
    opam switch create reproduce $ocaml_version || (echo 'you can remove the opam switch reproduce with:'; echo 'opam switch remove reproduce'; exit 1)
}

install_hol_light_deps() {
    line
    echo install HOL-Light dependencies ...
    opam install -y camlp5.$camlp5_version ocamlfind zarith
}

install_lambdapi() {
    line
    echo install lambdapi ...
    opam install -y lambdapi.$lambdapi_version
}

install_coq() {
    line
    echo install coq and package dependencies ...
    opam repo add coq-released https://coq.inria.fr/opam/released
    opam install -y coq.$coq_version
}

install_hol2dk() {
    line
    echo install hol2dk ...
    git clone https://github.com/Deducteam/hol2dk.git
    cd hol2dk
    git checkout $hol2dk_commit
    dune build && dune install
    cd ..
}

install_and_patch_hol_light() {
    line
    echo install and patch hol-light ...
    git clone https://github.com/jrh13/hol-light.git
    cd hol-light
    git checkout $hollight_commit
    make
    hol2dk patch
    cd ..
}

dump_proofs() {
    line
    echo extract hol-light proofs ...
    cd hol-light
    cp ../../$base.ml .
    hol2dk dump-simp$dump_simp_option $base.ml
    cd ..
}

translate_proofs() {
    line
    echo translate HOL-Light proofs to lambdapi and coq ...
    mkdir -p output
    cd output
    hol2dk link $base
    rm -f HOLLight.v
    cp ../../$require.v .
    make split
    make $jobs lp
    make $jobs v REQUIRE=$require
    cd ..
}

check_proofs() {
    line
    echo check proofs ...
    cd output
    make $jobs vo REQUIRE=$require
    make opam REQUIRE=$require
    cd ..
}

create_and_check_opam_library() {
    line
    echo create opam library ...
    mkdir -p opam
    cd output
    cp $require.v theory_hol.v ../opam
    sed -e "s/${base}_//g" ${base}_types.v > ../opam/types.v
    sed -e "s/${base}_//g" ${base}_terms.v > ../opam/terms.v
    sed -e "s/${base}_//g" ${base}_opam.v -e '/^Require Import axioms.$/d' > ../opam/theorems.v
    cd ../opam
    cp ../../Makefile .
    make
    cd ..
}

export HOLLIGHT_DIR=`pwd`/hol-light
export HOL2DK_DIR=`pwd`/hol2dk

setup_env() {
    create_opam_switch
    install_hol_light_deps
    install_lambdapi
    install_coq
    install_hol2dk
    install_and_patch_hol_light
}

setup_env
dump_proofs
translate_proofs
check_proofs
create_and_check_opam_library

line
echo remove opam switch reproduce ...
opam switch remove reproduce
